version: '3.8'

services:
  app:
    build:
      context: ./pipeline/deployment
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  airflow:
    image: apache/airflow:2.4.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@db:5432/mydatabase
    depends_on:
      - db
      - spark-master
    ports:
      - "8080:8080"  # Airflow UI port

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077"    # Spark master port
      - "8081:8081"    # Spark UI port
    volumes:
      - spark_logs:/opt/bitnami/spark/logs

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G        # Adjust memory for the worker
      - SPARK_WORKER_CORES=1          # Adjust cores for the worker
    depends_on:
      - spark-master
    volumes:
      - spark_logs:/opt/bitnami/spark/logs

volumes:
  postgres_data:
  spark_logs:
