apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.4.0
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "LocalExecutor"
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://user:password@postgres:5432/mydatabase"
        ports:
          - containerPort: 8080
