apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
  namespace: default  # Change if using a different namespace
  labels:
    app.kubernetes.io/name: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-operator
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-operator
          image: gcr.io/spark-operator/spark-operator:v1beta2-1.2.3-3.1.1
          args:
            - --namespace=default  
            - --enable-webhook      
